### ISSUE TITLE
Update docente 

### ISSUE THREAD

**Issue by razerr17** [razerr17/Grupo10#9]
- [x] Agregar docente - actualizado
- [x] Actualizar datos docente 
- [x] Incluir material-table

**Comment by Claudiars20** [comment]
- Para instalar package material-table: `npm install --legacy-peer-deps --save material-table@1.61.0`
- Video de referencia: https://www.youtube.com/watch?v=4TOONPrrlKY&t=1739s

**Comment by Claudiars20** [comment]
Culminado
